server:
  context-path: /
  port: 6060
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

# 图片保存的地址
imageFilePath: F:\project\Baisen1105-Film-master\Film\src\main\webapp\static\filmImage
